# Generated by Django 5.0.6 on 2025-01-22 14:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arxiv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('yil', models.CharField(blank=True, max_length=255, null=True)),
                ('nashr_raqami', models.CharField(blank=True, max_length=255, null=True)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('content_uz', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('content_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='image')),
                ('status', models.CharField(choices=[('published', 'Published'), ('not_published', 'Not Published')], default='published', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Arxiv',
                'verbose_name_plural': 'Arxivlar',
            },
        ),
        migrations.CreateModel(
            name='Avtoreferat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('cover_img', models.ImageField(blank=True, null=True, upload_to='images')),
                ('file', models.FileField(blank=True, null=True, upload_to='images')),
                ('status', models.CharField(choices=[('published', 'Published'), ('not_published', 'Not Published')], default='published', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Avtoreferat',
                'verbose_name_plural': 'Avtoreferat',
            },
        ),
        migrations.CreateModel(
            name='ElektronKitob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('cover_img', models.ImageField(blank=True, null=True, upload_to='images')),
                ('file', models.FileField(blank=True, null=True, upload_to='images')),
                ('status', models.CharField(choices=[('published', 'Published'), ('not_published', 'Not Published')], default='published', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Elektron Kitob',
                'verbose_name_plural': 'Elektron Kitob',
            },
        ),
        migrations.CreateModel(
            name='Manba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('title_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('cover_img', models.ImageField(blank=True, null=True, upload_to='images')),
                ('file', models.FileField(blank=True, null=True, upload_to='images')),
                ('status', models.CharField(choices=[('published', 'Published'), ('not_published', 'Not Published')], default='published', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Manbalar',
                'verbose_name_plural': 'Manbalar',
            },
        ),
        migrations.CreateModel(
            name='Tahrirchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('ish_joyi', models.CharField(max_length=255)),
                ('lavozimi', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('published', 'Published'), ('not_published', 'Not Published')], default='published', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tahririyat',
                'verbose_name_plural': 'Tahririyat',
            },
        ),
        migrations.CreateModel(
            name='Talablar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('content_uz', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('content_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('img_url', models.ImageField(blank=True, null=True, upload_to='images')),
                ('status', models.CharField(choices=[('published', 'Published'), ('not_published', 'Not Published')], default='published', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Talab',
                'verbose_name_plural': 'Talablar',
            },
        ),
    ]
