# Generated by Django 5.0.6 on 2025-02-13 12:04

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abstract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('title_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/Avtoreferat/image')),
                ('file', models.FileField(blank=True, null=True, upload_to='media/Avtoreferat/file/')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Disertatsiya va avtorefarat',
                'verbose_name_plural': 'Disertatsiya va avtorefaratlar',
            },
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('year', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='media/Arxiv/image')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Arxiv',
                'verbose_name_plural': 'Arxivlar',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='Comment/file')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('position_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('position_en', models.CharField(blank=True, max_length=255, null=True)),
                ('degree', models.CharField(blank=True, max_length=255, null=True)),
                ('degree_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('degree_en', models.CharField(blank=True, max_length=255, null=True)),
                ('sphere', models.CharField(blank=True, max_length=255, null=True)),
                ('sphere_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('sphere_en', models.CharField(blank=True, max_length=255, null=True)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('content_uz', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('content_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='media/tahririyat')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Tahririyat',
                'verbose_name_plural': 'Tahririyat',
            },
        ),
        migrations.CreateModel(
            name='Mat_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Mat category',
                'verbose_name_plural': 'Mat category',
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Period books',
                'verbose_name_plural': 'Period books',
            },
        ),
        migrations.CreateModel(
            name='Period_filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'arxiv hujjat filter',
                'verbose_name_plural': 'arxiv hujjat filter',
            },
        ),
        migrations.CreateModel(
            name='Region_filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Region filter',
                'verbose_name_plural': 'Region filter',
            },
        ),
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('title_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('content_uz', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('content_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('sub_content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('sub_content_uz', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('sub_content_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/talablar')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Talab',
                'verbose_name_plural': 'Talablar',
            },
        ),
        migrations.CreateModel(
            name='Year_filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Year filter',
                'verbose_name_plural': 'Year filter',
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('title_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Books/image')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('order', models.IntegerField(default=0)),
                ('period', models.ManyToManyField(related_name='books', to='kutobxona.period')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
        migrations.CreateModel(
            name='archive_documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('title_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='archive/image')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('order', models.IntegerField(default=0)),
                ('period_filter', models.ManyToManyField(related_name='documents', to='kutobxona.period_filter')),
            ],
            options={
                'verbose_name': 'arxiv hujjat',
                'verbose_name_plural': 'arxiv hujjatlar',
            },
        ),
        migrations.CreateModel(
            name='the_press',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('title_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='matbuot/image')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('order', models.IntegerField(default=0)),
                ('mat_cotegory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotegory', to='kutobxona.mat_category')),
                ('region_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='region', to='kutobxona.region_filter')),
                ('year_id', models.ManyToManyField(related_name='year', to='kutobxona.year_filter')),
            ],
            options={
                'verbose_name': 'Matbuot',
                'verbose_name_plural': 'Matbuotlar',
            },
        ),
    ]
