# Generated by Django 5.0.6 on 2025-02-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutobxona', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='the_press',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/matbuot/image'),
        ),
    ]
