# Generated by Django 5.0.6 on 2025-02-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutobxona', '0002_alter_the_press_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='the_press',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='matbuot/file'),
        ),
        migrations.AlterField(
            model_name='the_press',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='matbuot/image'),
        ),
    ]
