# Generated by Django 5.0.6 on 2025-01-31 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutobxona', '0002_elon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elon',
            name='content',
        ),
        migrations.AddField(
            model_name='elon',
            name='image',
            field=models.ImageField(default=2, upload_to='image'),
            preserve_default=False,
        ),
    ]
