# Generated by Django 5.0.6 on 2025-02-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutobxona', '0003_alter_the_press_file_alter_the_press_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mat_category',
            name='image',
            field=models.ImageField(default=2, upload_to='images/'),
            preserve_default=False,
        ),
    ]
