# Generated by Django 5.0.6 on 2025-01-31 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kutobxona', '0003_remove_elon_content_elon_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='elon',
        ),
    ]
