# Generated by Django 5.0.6 on 2025-02-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutobxona', '0004_mat_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Literature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('title_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Adabiyot/image')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Adabiyot',
                'verbose_name_plural': 'Adabiyotlar',
            },
        ),
        migrations.CreateModel(
            name='Sources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('title_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Manbalar/image')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Manbalar',
                'verbose_name_plural': 'Manbalar',
            },
        ),
        migrations.RemoveField(
            model_name='books',
            name='period',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.RemoveField(
            model_name='the_press',
            name='mat_cotegory',
        ),
        migrations.RemoveField(
            model_name='archive_documents',
            name='period_filter',
        ),
        migrations.RemoveField(
            model_name='the_press',
            name='region_id',
        ),
        migrations.RemoveField(
            model_name='the_press',
            name='year_id',
        ),
        migrations.AlterModelOptions(
            name='abstract',
            options={'verbose_name': 'Avtorefarat', 'verbose_name_plural': 'Avtorefaratlar'},
        ),
        migrations.DeleteModel(
            name='Books',
        ),
        migrations.DeleteModel(
            name='Period',
        ),
        migrations.DeleteModel(
            name='Mat_category',
        ),
        migrations.DeleteModel(
            name='Period_filter',
        ),
        migrations.DeleteModel(
            name='Region_filter',
        ),
        migrations.DeleteModel(
            name='the_press',
        ),
        migrations.DeleteModel(
            name='Year_filter',
        ),
    ]
