# Generated by Django 5.0.6 on 2025-02-20 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kutobxona', '0005_literature_sources_remove_books_period_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='archive_documents',
        ),
    ]
