# Generated by Django 5.0.9 on 2025-02-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutobxona', '0006_delete_archive_documents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editorial',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='editorial',
            name='degree_en',
        ),
        migrations.RemoveField(
            model_name='editorial',
            name='degree_uz',
        ),
        migrations.RemoveField(
            model_name='editorial',
            name='file',
        ),
        migrations.RemoveField(
            model_name='editorial',
            name='position',
        ),
        migrations.RemoveField(
            model_name='editorial',
            name='position_en',
        ),
        migrations.RemoveField(
            model_name='editorial',
            name='position_uz',
        ),
        migrations.RemoveField(
            model_name='editorial',
            name='sphere',
        ),
        migrations.RemoveField(
            model_name='editorial',
            name='sphere_en',
        ),
        migrations.RemoveField(
            model_name='editorial',
            name='sphere_uz',
        ),
        migrations.AddField(
            model_name='editorial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/tahririyat'),
        ),
    ]
