# Generated by Django 5.0.9 on 2025-03-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutobxona', '0007_remove_editorial_degree_remove_editorial_degree_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstract',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='Avtoreferat/file'),
        ),
        migrations.AlterField(
            model_name='abstract',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Avtoreferat/image'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='Arxiv/file'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='Arxiv/image'),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tahririyat/image'),
        ),
        migrations.AlterField(
            model_name='literature',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='Adabiyot/image'),
        ),
        migrations.AlterField(
            model_name='requirements',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='talablar/image'),
        ),
        migrations.AlterField(
            model_name='sources',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='Manbalar/file'),
        ),
    ]
