# Generated by Django 5.0.6 on 2025-01-22 14:43

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarkazlarBolimlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('title_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('tarix', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('tarix_uz', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('tarix_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('published', 'Published'), ('not_published', 'Not Published')], default='published', max_length=20, null=True)),
                ('order', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Markazlar bo'limi",
                'verbose_name_plural': "Markazlar bo'limlari",
            },
        ),
        migrations.CreateModel(
            name='Rasmlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotogalereya', models.ImageField(blank=True, max_length=255, null=True, upload_to='images')),
                ('silder', models.ImageField(blank=True, max_length=255, null=True, upload_to='images')),
                ('markazlar_bolimlar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rasmlar', to='markazlar_va_bolimlar.markazlarbolimlar')),
            ],
            options={
                'verbose_name': 'Rasmlar',
                'verbose_name_plural': 'Rasmlar',
            },
        ),
        migrations.CreateModel(
            name='Xodimlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_uz', models.CharField(max_length=255, null=True)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('lavozim', models.CharField(max_length=255)),
                ('lavozim_uz', models.CharField(max_length=255, null=True)),
                ('lavozim_en', models.CharField(max_length=255, null=True)),
                ('ilmiy_daraja', models.CharField(max_length=255)),
                ('ilmiy_daraja_uz', models.CharField(max_length=255, null=True)),
                ('ilmiy_daraja_en', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(choices=[('published', 'Published'), ('not_published', 'Not Published')], default='published', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('markazlar_bolimlar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xodimlar', to='markazlar_va_bolimlar.markazlarbolimlar')),
            ],
            options={
                'verbose_name': 'Xodim',
                'verbose_name_plural': 'Xodimlar',
            },
        ),
    ]
