# Generated by Django 5.0.9 on 2025-03-07 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markazlar_va_bolimlar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xodimlar',
            name='email',
        ),
        migrations.RemoveField(
            model_name='xodimlar',
            name='email_en',
        ),
        migrations.RemoveField(
            model_name='xodimlar',
            name='email_uz',
        ),
        migrations.AddField(
            model_name='xodimlar',
            name='degree',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='xodimlar',
            name='degree_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='xodimlar',
            name='degree_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
