# Generated by Django 5.0.6 on 2025-02-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markazlar_va_bolimlar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xodimlar',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='xodimlar/file'),
        ),
    ]
