# Generated by Django 5.0.6 on 2025-01-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markazlar_va_bolimlar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xodimlar',
            name='batafsil',
            field=models.FileField(blank=True, null=True, upload_to='media/Xodimlar/file'),
        ),
    ]
