# Generated by Django 5.0.9 on 2025-03-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markazlar_va_bolimlar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolimlar',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='Bolimlar/image'),
        ),
        migrations.AddField(
            model_name='markazlar',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='Bolimlar/image'),
        ),
        migrations.AddField(
            model_name='xodimlar',
            name='surname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='xodimlar',
            name='surname_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='xodimlar',
            name='surname_uz',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xodimlar',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xodimlar',
            name='full_name_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xodimlar',
            name='full_name_uz',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
