# Generated by Django 5.0.6 on 2025-02-11 07:02

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markazlar_va_bolimlar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolimlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('title_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('content_uz', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('content_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/Bolimlar')),
                ('status', models.CharField(blank=True, choices=[('published', 'Published'), ('not_published', 'Not Published')], default='published', max_length=20, null=True)),
                ('order', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Bo'limlar",
                'verbose_name_plural': "Bo'limlar",
            },
        ),
        migrations.CreateModel(
            name='Markazlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('title_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('content_uz', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('content_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/Markazlar')),
                ('status', models.CharField(blank=True, choices=[('published', 'Published'), ('not_published', 'Not Published')], default='published', max_length=20, null=True)),
                ('order', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Markazlar',
                'verbose_name_plural': 'Markazlar',
            },
        ),
        migrations.RemoveField(
            model_name='xodimlar',
            name='center_id',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='center_id',
        ),
        migrations.RemoveField(
            model_name='tadqiqot',
            name='center_id',
        ),
        migrations.RemoveField(
            model_name='video',
            name='center_id',
        ),
        migrations.AddField(
            model_name='photo',
            name='bolimlar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='markazlar_va_bolimlar.bolimlar'),
        ),
        migrations.AddField(
            model_name='tadqiqot',
            name='bolimlar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tadqiqot', to='markazlar_va_bolimlar.bolimlar'),
        ),
        migrations.AddField(
            model_name='video',
            name='bolimlar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video', to='markazlar_va_bolimlar.bolimlar'),
        ),
        migrations.AddField(
            model_name='xodimlar',
            name='bolimlar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xodimlar', to='markazlar_va_bolimlar.bolimlar'),
        ),
        migrations.AddField(
            model_name='photo',
            name='markazlar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='markazlar_va_bolimlar.markazlar'),
        ),
        migrations.AddField(
            model_name='tadqiqot',
            name='markazlar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tadqiqotlar', to='markazlar_va_bolimlar.markazlar'),
        ),
        migrations.AddField(
            model_name='video',
            name='markazlar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='markazlar_va_bolimlar.markazlar'),
        ),
        migrations.AddField(
            model_name='xodimlar',
            name='markazlar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xodim', to='markazlar_va_bolimlar.markazlar'),
        ),
        migrations.DeleteModel(
            name='Markazlar_Bolimlar',
        ),
    ]
