# Generated by Django 5.0.6 on 2025-02-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markazlar_va_bolimlar', '0002_bolimlar_markazlar_remove_xodimlar_center_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xodimlar',
            options={'verbose_name': 'Xodim', 'verbose_name_plural': 'Xodimlar'},
        ),
        migrations.RemoveField(
            model_name='bolimlar',
            name='status',
        ),
        migrations.RemoveField(
            model_name='markazlar',
            name='status',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='order',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='status',
        ),
        migrations.RemoveField(
            model_name='tadqiqot',
            name='status',
        ),
        migrations.RemoveField(
            model_name='video',
            name='order',
        ),
        migrations.RemoveField(
            model_name='video',
            name='status',
        ),
        migrations.RemoveField(
            model_name='xodimlar',
            name='academic_degree',
        ),
        migrations.RemoveField(
            model_name='xodimlar',
            name='academic_degree_en',
        ),
        migrations.RemoveField(
            model_name='xodimlar',
            name='academic_degree_uz',
        ),
        migrations.RemoveField(
            model_name='xodimlar',
            name='email',
        ),
        migrations.RemoveField(
            model_name='xodimlar',
            name='position',
        ),
        migrations.RemoveField(
            model_name='xodimlar',
            name='position_en',
        ),
        migrations.RemoveField(
            model_name='xodimlar',
            name='position_uz',
        ),
        migrations.RemoveField(
            model_name='xodimlar',
            name='sphere',
        ),
        migrations.RemoveField(
            model_name='xodimlar',
            name='sphere_en',
        ),
        migrations.RemoveField(
            model_name='xodimlar',
            name='sphere_uz',
        ),
        migrations.RemoveField(
            model_name='xodimlar',
            name='status',
        ),
        migrations.RemoveField(
            model_name='xodimlar',
            name='title',
        ),
        migrations.RemoveField(
            model_name='xodimlar',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='xodimlar',
            name='title_uz',
        ),
        migrations.AddField(
            model_name='xodimlar',
            name='activity',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='xodimlar',
            name='activity_en',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='xodimlar',
            name='activity_uz',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='xodimlar',
            name='ful_name',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xodimlar',
            name='ful_name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='xodimlar',
            name='ful_name_uz',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
