# Generated by Django 5.0.6 on 2025-02-18 11:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markazlar_va_bolimlar', '0002_xodimlar_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xodimlar',
            name='activity',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xodimlar',
            name='activity_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xodimlar',
            name='activity_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
