# Generated by Django 5.0.9 on 2025-03-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markazlar_va_bolimlar', '0002_remove_xodimlar_email_remove_xodimlar_email_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xodimlar',
            old_name='ful_name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='xodimlar',
            old_name='ful_name_en',
            new_name='full_name_en',
        ),
        migrations.RemoveField(
            model_name='xodimlar',
            name='ful_name_uz',
        ),
        migrations.AddField(
            model_name='xodimlar',
            name='full_name_uz',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
