# Generated by Django 5.0.9 on 2025-03-19 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markazlar_va_bolimlar', '0002_bolimlar_file_markazlar_file_xodimlar_surname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
