# Generated by Django 5.0.9 on 2025-03-28 07:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markazlar_va_bolimlar', '0003_audio_order_video_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='xodimlar',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='xodimlar',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='xodimlar',
            name='works',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='xodimlar',
            name='works_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='xodimlar',
            name='works_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
