# Generated by Django 5.1.7 on 2025-04-04 11:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markazlar_va_bolimlar', '0004_xodimlar_email_xodimlar_phone_xodimlar_works_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolimlar',
            name='content_two',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bolimlar',
            name='content_two_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bolimlar',
            name='content_two_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='markazlar',
            name='content_two',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='markazlar',
            name='content_two_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='markazlar',
            name='content_two_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
