# Generated by Django 5.0.9 on 2025-03-01 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markazlar_va_bolimlar', '0004_remove_video_bolimlar_remove_video_markazlar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('title_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('audio', models.FileField(blank=True, null=True, upload_to='Audio')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Audio/iamge')),
            ],
            options={
                'verbose_name': 'Audiolar',
                'verbose_name_plural': 'Audiolar',
            },
        ),
        migrations.CreateModel(
            name='Rasm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('title_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Rasmlar')),
            ],
            options={
                'verbose_name': 'Rasmlar',
                'verbose_name_plural': 'Rasmlar',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('title_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='Video')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Video/iamge')),
                ('link', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Videolar',
                'verbose_name_plural': 'Videolar',
            },
        ),
        migrations.CreateModel(
            name='Audiolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(blank=True, null=True, upload_to='Audio/audiolar')),
                ('audio_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Audiolar', to='markazlar_va_bolimlar.audio')),
            ],
            options={
                'verbose_name': 'Audiolar',
                'verbose_name_plural': 'Audiolar',
            },
        ),
        migrations.CreateModel(
            name='Rasmlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Rasmlar/image')),
                ('image_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Rasmlar', to='markazlar_va_bolimlar.rasm')),
            ],
            options={
                'verbose_name': 'Rasmlar',
                'verbose_name_plural': 'Rasmlar',
            },
        ),
        migrations.CreateModel(
            name='Videolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='Video/videos')),
                ('video_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Videolar', to='markazlar_va_bolimlar.video')),
            ],
            options={
                'verbose_name': 'Videolar',
                'verbose_name_plural': 'Videolar',
            },
        ),
    ]
