# Generated by Django 5.0.9 on 2025-06-23 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markazlar_va_bolimlar', '0005_bolimlar_content_two_bolimlar_content_two_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tadqiqot',
            name='bolimlar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tadqiqot_bolim', to='markazlar_va_bolimlar.bolimlar'),
        ),
        migrations.AlterField(
            model_name='tadqiqot',
            name='markazlar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tadqiqot_markaz', to='markazlar_va_bolimlar.markazlar'),
        ),
        migrations.AlterField(
            model_name='xodimlar',
            name='bolimlar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xodimlar_bolim', to='markazlar_va_bolimlar.bolimlar'),
        ),
        migrations.AlterField(
            model_name='xodimlar',
            name='markazlar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xodimlar_markaz', to='markazlar_va_bolimlar.markazlar'),
        ),
    ]
