# Generated by Django 5.0.9 on 2025-03-01 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markazlar_va_bolimlar', '0005_audio_rasm_video_audiolar_rasmlar_videolar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xodimlar',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='xodimlar',
            name='activity_en',
        ),
        migrations.RemoveField(
            model_name='xodimlar',
            name='activity_uz',
        ),
        migrations.RemoveField(
            model_name='xodimlar',
            name='file',
        ),
        migrations.RemoveField(
            model_name='xodimlar',
            name='works',
        ),
        migrations.RemoveField(
            model_name='xodimlar',
            name='works_en',
        ),
        migrations.RemoveField(
            model_name='xodimlar',
            name='works_uz',
        ),
    ]
