# Generated by Django 5.0.9 on 2025-03-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markazlar_va_bolimlar', '0006_remove_xodimlar_activity_remove_xodimlar_activity_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolimlar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Bolimlar/image'),
        ),
        migrations.AlterField(
            model_name='markazlar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Markazlar/image'),
        ),
        migrations.AlterField(
            model_name='tadqiqot',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Tadqiqot/image'),
        ),
        migrations.AlterField(
            model_name='xodimlar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Xodimlar/image'),
        ),
    ]
