# Generated by Django 5.0.6 on 2025-03-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markazlar_va_bolimlar', '0007_alter_bolimlar_image_alter_markazlar_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Audio/image'),
        ),
        migrations.AlterField(
            model_name='video',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Video/image'),
        ),
    ]
