# Generated by Django 5.0.6 on 2025-03-02 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markazlar_va_bolimlar', '0008_alter_audio_image_alter_video_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videolar',
            name='video_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videolar', to='markazlar_va_bolimlar.video'),
        ),
    ]
