# Generated by Django 5.0.6 on 2025-03-02 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markazlar_va_bolimlar', '0010_alter_video_options_alter_videolar_video_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audio',
            options={'verbose_name': 'Audio', 'verbose_name_plural': 'Audio'},
        ),
        migrations.AlterModelOptions(
            name='rasm',
            options={'verbose_name': 'Rasm', 'verbose_name_plural': 'Rasm'},
        ),
    ]
