# Generated by Django 5.0.6 on 2025-03-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markazlar_va_bolimlar', '0011_alter_audio_options_alter_rasm_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rasm',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Rasm'),
        ),
        migrations.AlterField(
            model_name='rasmlar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Rasm/image'),
        ),
    ]
