# Generated by Django 5.0.6 on 2025-03-05 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markazlar_va_bolimlar', '0012_alter_rasm_image_alter_rasmlar_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='xodimlar',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='xodimlar',
            name='email_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='xodimlar',
            name='email_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='xodimlar',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='xodimlar',
            name='position_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='xodimlar',
            name='position_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='xodimlar',
            name='ful_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='xodimlar',
            name='ful_name_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='xodimlar',
            name='ful_name_uz',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
