# Generated by Django 5.0.6 on 2025-03-05 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markazlar_va_bolimlar', '0013_xodimlar_email_xodimlar_email_en_xodimlar_email_uz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xodimlar',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='xodimlar',
            name='email_en',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='xodimlar',
            name='email_uz',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
