# Generated by Django 5.0.6 on 2025-01-22 14:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Azolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shifr', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('name_uz', models.CharField(max_length=255, null=True)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('ish_joy', models.CharField(max_length=255)),
                ('ish_joy_uz', models.CharField(max_length=255, null=True)),
                ('ish_joy_en', models.CharField(max_length=255, null=True)),
                ('lavozim', models.CharField(max_length=255)),
                ('lavozim_uz', models.CharField(max_length=255, null=True)),
                ('lavozim_en', models.CharField(max_length=255, null=True)),
                ('ilmiy_darajasi', models.CharField(max_length=255)),
                ('ilmiy_darajasi_uz', models.CharField(max_length=255, null=True)),
                ('ilmiy_darajasi_en', models.CharField(max_length=255, null=True)),
                ('ilmiy_unvoni', models.CharField(max_length=255)),
                ('ilmiy_unvoni_uz', models.CharField(max_length=255, null=True)),
                ('ilmiy_unvoni_en', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(choices=[('published', 'Published'), ('not_published', 'Not Published')], default='published', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Azolar',
                'verbose_name_plural': 'Azolar',
            },
        ),
        migrations.CreateModel(
            name='fon_picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('content_uz', models.TextField(blank=True, null=True)),
                ('content_en', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='images')),
                ('status', models.CharField(choices=[('published', 'Published'), ('not_published', 'Not Published')], default='published', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'fon_picture',
                'verbose_name_plural': 'fon_picture',
            },
        ),
        migrations.CreateModel(
            name='Ilmiy_kengash_majlis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('content_uz', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('content_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='images')),
                ('date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('published', 'Published'), ('not_published', 'Not Published')], default='published', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ilmiy kengash majlis',
                'verbose_name_plural': 'Ilmiy kengash majlis',
            },
        ),
        migrations.CreateModel(
            name='Yosh_olimlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('content_uz', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('content_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='images')),
                ('status', models.CharField(choices=[('published', 'Published'), ('not_published', 'Not Published')], default='published', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Yosh olim',
                'verbose_name_plural': 'Yosh olimlar',
            },
        ),
    ]
