# Generated by Django 5.0.6 on 2025-02-27 06:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kengashlar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elonlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('content_uz', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('content_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Elonlar',
                'verbose_name_plural': 'Elonlar',
            },
        ),
        migrations.RenameField(
            model_name='azolar',
            old_name='contact',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='azolar',
            old_name='degree_en',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='azolar',
            old_name='degree_uz',
            new_name='title_uz',
        ),
        migrations.RemoveField(
            model_name='azolar',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='azolar',
            name='email',
        ),
        migrations.RemoveField(
            model_name='azolar',
            name='name',
        ),
        migrations.RemoveField(
            model_name='azolar',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='azolar',
            name='name_uz',
        ),
        migrations.RemoveField(
            model_name='azolar',
            name='order',
        ),
        migrations.RemoveField(
            model_name='azolar',
            name='position',
        ),
        migrations.RemoveField(
            model_name='azolar',
            name='position_en',
        ),
        migrations.RemoveField(
            model_name='azolar',
            name='position_uz',
        ),
        migrations.RemoveField(
            model_name='ilmiy_kengash_majlis',
            name='date',
        ),
        migrations.RemoveField(
            model_name='ilmiy_kengash_majlis',
            name='file',
        ),
        migrations.AddField(
            model_name='azolar',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='azolar',
            name='content_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='azolar',
            name='content_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
