# Generated by Django 5.0.6 on 2025-02-12 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kengashlar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='azolar',
            name='status',
        ),
        migrations.RemoveField(
            model_name='ilmiy_kengash_majlis',
            name='order',
        ),
        migrations.RemoveField(
            model_name='ilmiy_kengash_majlis',
            name='status',
        ),
        migrations.RemoveField(
            model_name='yosh_olimlar',
            name='order',
        ),
        migrations.RemoveField(
            model_name='yosh_olimlar',
            name='status',
        ),
    ]
