# Generated by Django 5.0.6 on 2025-02-27 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kengashlar', '0003_alter_azolar_title_alter_azolar_title_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elonlar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Elonlar/image'),
        ),
    ]
