# Generated by Django 5.0.9 on 2025-03-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kengashlar', '0004_elonlar_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yosh_olimlar',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='Yosh_olimlar/images'),
        ),
    ]
