# Generated by Django 5.0.9 on 2025-03-07 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kengashlar', '0007_kadirlar_academic_title_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kadirlar',
            options={'verbose_name': 'Kadirlar', 'verbose_name_plural': 'Kadirlar'},
        ),
        migrations.AlterModelOptions(
            name='xodimlar',
            options={'verbose_name': 'Xodimlar', 'verbose_name_plural': 'Xodimlar'},
        ),
    ]
