# Generated by Django 5.0.9 on 2025-03-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kengashlar', '0008_alter_kadirlar_options_alter_xodimlar_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='kadirlar',
            name='shifri',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kadirlar',
            name='shifri_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kadirlar',
            name='shifri_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kadirlar',
            name='workplace',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kadirlar',
            name='workplace_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kadirlar',
            name='workplace_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
