# Generated by Django 5.0.9 on 2025-03-07 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kengashlar', '0009_kadirlar_shifri_kadirlar_shifri_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kadirlar',
            name='shifri_en',
        ),
        migrations.RemoveField(
            model_name='kadirlar',
            name='shifri_uz',
        ),
    ]
