# Generated by Django 5.0.9 on 2025-03-07 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kengashlar', '0010_remove_kadirlar_shifri_en_remove_kadirlar_shifri_uz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xodimlar',
            name='center_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xodimlar', to='kengashlar.ilmiy_kengash_majlis'),
        ),
    ]
