# Generated by Django 5.0.9 on 2025-03-14 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kengashlar', '0011_alter_xodimlar_center_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='xodimlar',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='xodimlar',
            name='position_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='xodimlar',
            name='position_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
