# Generated by Django 5.1.7 on 2025-03-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kengashlar', '0013_content_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='elonlar',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
