# Generated by Django 5.1.7 on 2025-04-26 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kengashlar', '0014_elonlar_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoshXodim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Xodimlar/images/')),
                ('yosh_olim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yosh_xodimlar', to='kengashlar.yosh_olimlar')),
            ],
        ),
    ]
