# Generated by Django 5.1.7 on 2025-05-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kengashlar', '0015_yoshxodim'),
    ]

    operations = [
        migrations.AddField(
            model_name='elonlar',
            name='fullname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
