# Generated by Django 5.2.5 on 2025-08-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kengashlar', '0016_elonlar_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='xodimlar',
            name='lavozim',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='xodimlar',
            name='lavozim_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='xodimlar',
            name='lavozim_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
