# Generated by Django 5.0.6 on 2025-01-31 11:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tadqiqot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('content_uz', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('content_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('img_file', models.ImageField(blank=True, null=True, upload_to='images')),
                ('status', models.CharField(choices=[('published', 'Published'), ('not_published', 'Not Published')], default='published', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tadqiqot',
                'verbose_name_plural': 'Tadqiqot',
            },
        ),
        migrations.CreateModel(
            name='Xalqaro_sayohatlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('content_uz', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('content_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('subcontent', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('subcontent_uz', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('subcontent_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='images')),
                ('status', models.CharField(choices=[('published', 'Published'), ('not_published', 'Not Published')], default='published', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Xalqaro sayohat',
                'verbose_name_plural': 'Xalqaro sayohatlar',
            },
        ),
        migrations.CreateModel(
            name='Xamkor_loihalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('title_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('content_uz', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('content_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('img_file', models.ImageField(blank=True, null=True, upload_to='images')),
                ('status', models.CharField(choices=[('published', 'Published'), ('not_published', 'Not Published')], default='published', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Xamkor loiha',
                'verbose_name_plural': 'Xamkor loihalar',
            },
        ),
        migrations.CreateModel(
            name='Xamkor_tashkilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('content_uz', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('content_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='images')),
                ('status', models.CharField(choices=[('published', 'Published'), ('not_published', 'Not Published')], default='published', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Xamkor tashkilot',
                'verbose_name_plural': 'Xamkor tashkilotlar',
            },
        ),
    ]
