# Generated by Django 5.0.6 on 2025-02-11 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xalqaro_aloqalar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xalqaro_sayohatlar',
            options={'verbose_name': 'Ilmiy safarlar', 'verbose_name_plural': 'Ilmiy safarlar'},
        ),
    ]
