# Generated by Django 5.0.6 on 2025-02-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xalqaro_aloqalar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xamkor_loihalar',
            name='status',
            field=models.CharField(choices=[('Bajarilgan loyihalar', 'Bajarilgan loyihalar'), ('Amaldagi loyihalar', 'Amaldagi loyihalar')], default='Bajarilgan loyihalar', max_length=20),
        ),
    ]
