# Generated by Django 5.0.6 on 2025-02-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xalqaro_aloqalar', '0002_xamkor_loihalar_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xamkor_loihalar',
            name='status',
            field=models.CharField(choices=[('Bajarilgan loyihalar', 'Bajarilgan loyihalar'), ('Amaldagi loyihalar', 'Amaldagi loyihalar')], default='Bajarilgan loyihalar', max_length=30),
        ),
    ]
