# Generated by Django 5.0.6 on 2025-02-12 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xalqaro_aloqalar', '0002_alter_xalqaro_sayohatlar_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tadqiqot',
            name='status',
        ),
        migrations.RemoveField(
            model_name='xalqaro_sayohatlar',
            name='status',
        ),
        migrations.RemoveField(
            model_name='xamkor_loihalar',
            name='status',
        ),
        migrations.RemoveField(
            model_name='xamkor_tashkilot',
            name='status',
        ),
    ]
