# Generated by Django 5.0.6 on 2025-02-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qoshimcha_malumotlar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xabarlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ism')),
                ('phone', models.CharField(max_length=255, verbose_name='Telefon')),
                ('content', models.TextField(verbose_name='Xabar matni')),
            ],
        ),
        migrations.RemoveField(
            model_name='aloqa',
            name='faks',
        ),
    ]
