# Generated by Django 5.0.6 on 2025-02-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qoshimcha_malumotlar', '0002_xabarlar_remove_aloqa_faks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xabarlar',
            name='content',
            field=models.TextField(verbose_name='Xabar'),
        ),
    ]
