# Generated by Django 5.0.6 on 2025-02-27 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qoshimcha_malumotlar', '0002_category_kadirlar_bolim'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kadirlar_bolim',
            options={'verbose_name': 'Kadirlar bolimi', 'verbose_name_plural': 'Kadirlar bolimi'},
        ),
    ]
