# Generated by Django 5.0.9 on 2025-03-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qoshimcha_malumotlar', '0003_alter_kadirlar_bolim_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direktorlar',
            name='image',
            field=models.ImageField(upload_to='Direktorlar/image'),
        ),
        migrations.AlterField(
            model_name='havolalar',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='Havolalar/images'),
        ),
        migrations.AlterField(
            model_name='institut_tarixi',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Institut_tarixi/images'),
        ),
        migrations.AlterField(
            model_name='karusel',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='Karusel/images'),
        ),
        migrations.AlterField(
            model_name='rahbariyat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Rahbariyat/images'),
        ),
        migrations.AlterField(
            model_name='tashkiliy_tuzulma',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='Tashkiliy_tuzulma/images'),
        ),
        migrations.AlterField(
            model_name='yangiliklar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Yangiliklar/images'),
        ),
    ]
