# Generated by Django 5.0.6 on 2025-02-05 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qoshimcha_malumotlar', '0003_alter_xabarlar_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xabarlar',
            options={'verbose_name': 'Xabarlar', 'verbose_name_plural': 'Xabarlar'},
        ),
    ]
