# Generated by Django 5.0.6 on 2025-03-04 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qoshimcha_malumotlar', '0004_alter_direktorlar_image_alter_havolalar_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xodimlar_turlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Xodimlar_turlari',
                'verbose_name_plural': 'Xodimlar_turlari',
            },
        ),
        migrations.CreateModel(
            name='Xodimlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('full_name_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('full_name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Xodimlar/image')),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Xodimlar', to='qoshimcha_malumotlar.xodimlar_turlari')),
            ],
            options={
                'verbose_name': 'Xodimlar',
                'verbose_name_plural': 'Xodimlar',
            },
        ),
        migrations.DeleteModel(
            name='Direktorlar',
        ),
    ]
