# Generated by Django 5.0.6 on 2025-02-12 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qoshimcha_malumotlar', '0004_alter_xabarlar_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aloqa',
            name='order',
        ),
        migrations.RemoveField(
            model_name='aloqa',
            name='status',
        ),
        migrations.RemoveField(
            model_name='havolalar',
            name='status',
        ),
        migrations.RemoveField(
            model_name='rahbariyat',
            name='status',
        ),
        migrations.RemoveField(
            model_name='tashkiliy_tuzulma',
            name='status',
        ),
        migrations.RemoveField(
            model_name='yangiliklar',
            name='status',
        ),
    ]
