# Generated by Django 5.0.6 on 2025-02-13 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qoshimcha_malumotlar', '0005_remove_aloqa_order_remove_aloqa_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institut_tarixi',
            name='status',
        ),
    ]
