# Generated by Django 5.0.6 on 2025-03-04 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qoshimcha_malumotlar', '0005_xodimlar_turlari_xodimlar_delete_direktorlar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xodimlar_turlari',
            options={'verbose_name': 'Xodimlar turlari', 'verbose_name_plural': 'Xodimlar turlari'},
        ),
    ]
