# Generated by Django 5.0.6 on 2025-03-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qoshimcha_malumotlar', '0006_alter_xodimlar_turlari_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='xodimlar',
            name='year',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
