# Generated by Django 5.0.9 on 2025-03-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qoshimcha_malumotlar', '0008_yangiliklar_link_alter_institut_tarixi_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yangiliklar',
            name='created_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
