# Generated by Django 5.0.9 on 2025-03-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qoshimcha_malumotlar', '0009_alter_yangiliklar_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='xodimlar',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='xodimlar_turlari',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
