# Generated by Django 5.0.9 on 2025-03-28 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qoshimcha_malumotlar', '0010_xodimlar_order_xodimlar_turlari_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xodimlar_turlari',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='xodimlar_turlari',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='xodimlar_turlari',
            name='title_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
