# Generated by Django 5.0.9 on 2025-03-28 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qoshimcha_malumotlar', '0011_alter_xodimlar_turlari_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xodimlar',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Xodimlar', to='qoshimcha_malumotlar.xodimlar_turlari'),
        ),
    ]
