# Generated by Django 5.2.5 on 2025-08-11 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qoshimcha_malumotlar', '0012_alter_xodimlar_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='rahbariyat',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
