# Generated by Django 5.2.5 on 2025-08-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qoshimcha_malumotlar', '0013_rahbariyat_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='rahbariyat',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rahbariyat',
            name='description_uz',
            field=models.TextField(blank=True, null=True),
        ),
    ]
