# Generated by Django 5.0.6 on 2025-01-22 14:43

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seminar_turlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(choices=[('published', 'Published'), ('not_published', 'Not Published')], default='published', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Seminar turi',
                'verbose_name_plural': 'Seminar turlari',
            },
        ),
        migrations.CreateModel(
            name='Seminar_majlislari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('content_uz', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('content_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('subcontent', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('subcontent_uz', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('subcontent_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='media/Seminar_majlislari/files/')),
                ('data', models.DateField()),
                ('status', models.CharField(choices=[('published', 'Published'), ('not_published', 'Not Published')], default='published', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seminar_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seminar.seminar_turlari')),
            ],
            options={
                'verbose_name': 'Seminar majlisi',
                'verbose_name_plural': 'Seminar majlislari',
            },
        ),
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('subcontent', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('subcontent_uz', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('subcontent_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('published', 'Published'), ('not_published', 'Not Published')], default='published', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seminar_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seminar.seminar_turlari')),
            ],
            options={
                'verbose_name': 'Seminar',
                'verbose_name_plural': 'Seminarlar',
            },
        ),
    ]
