# Generated by Django 5.0.9 on 2025-03-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Seminar/image'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='title_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
