# Generated by Django 5.0.6 on 2025-02-12 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seminar',
            name='status',
        ),
        migrations.RemoveField(
            model_name='seminar_majlislari',
            name='status',
        ),
        migrations.RemoveField(
            model_name='seminar_turlari',
            name='status',
        ),
    ]
