# Generated by Django 5.0.6 on 2025-02-12 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0002_remove_seminar_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seminar',
            old_name='subcontent',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='seminar',
            old_name='subcontent_en',
            new_name='content_en',
        ),
        migrations.RenameField(
            model_name='seminar',
            old_name='subcontent_uz',
            new_name='content_uz',
        ),
        migrations.RemoveField(
            model_name='seminar',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='seminar',
            name='order',
        ),
        migrations.RemoveField(
            model_name='seminar',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='seminar_turlari',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='seminar_turlari',
            name='updated_at',
        ),
        migrations.DeleteModel(
            name='Seminar_majlislari',
        ),
    ]
