# Generated by Django 5.0.6 on 2025-01-31 11:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doktarantura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('labor_activity', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('labor_activity_uz', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('labor_activity_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('scientific_activity', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('scientific_activity_uz', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('scientific_activity_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('works', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('works_uz', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('works_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='media/Doktarantura/files/')),
                ('type', models.CharField(choices=[('doctaurant', 'Doctaurant'), ('basic', 'Basic')], default='doctaurant', max_length=20)),
                ('status', models.CharField(choices=[('published', 'Published'), ('not_published', 'Not Published')], default='published', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Doktarantura',
                'verbose_name_plural': 'Doktaranturalar',
            },
        ),
        migrations.CreateModel(
            name='Malakaviy_imtihon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('content_uz', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('content_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='media/Malakaviy_imtihon/files/')),
                ('status', models.CharField(choices=[('published', 'Published'), ('not_published', 'Not Published')], default='published', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Malakaviy imtihon',
                'verbose_name_plural': 'Malakaviy imtihonlar',
            },
        ),
        migrations.CreateModel(
            name='Qabul_tartibi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('content_uz', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('content_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='media/Qabul_tartibi/files/')),
                ('status', models.CharField(choices=[('published', 'Published'), ('not_published', 'Not Published')], default='published', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Qabul tartibi',
                'verbose_name_plural': 'Qabul tashkilotlar',
            },
        ),
    ]
