# Generated by Django 5.0.9 on 2025-03-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doktarantura', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doktarantura',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='Doktarantura/file'),
        ),
        migrations.AlterField(
            model_name='malakaviy_imtihon',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='Malakaviy_imtihon/file'),
        ),
        migrations.AlterField(
            model_name='qabul_tartibi',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='Qabul_tartibi/file'),
        ),
    ]
