# Generated by Django 5.0.6 on 2025-02-12 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doktarantura', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doktarantura',
            name='status',
        ),
        migrations.RemoveField(
            model_name='doktarantura',
            name='type',
        ),
        migrations.RemoveField(
            model_name='malakaviy_imtihon',
            name='status',
        ),
        migrations.RemoveField(
            model_name='qabul_tartibi',
            name='status',
        ),
    ]
