# Generated by Django 5.0.9 on 2025-03-19 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doktarantura', '0002_alter_doktarantura_file_alter_malakaviy_imtihon_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doktarantura',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doktarantura',
            name='full_name_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doktarantura',
            name='full_name_uz',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doktarantura',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doktarantura',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doktarantura',
            name='title_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
